-- Seed company templates with popular tech companies
INSERT INTO public.company_templates (name, slug, logo_url, industry, description, difficulty, common_roles) VALUES
('Google', 'google', 'https://logo.clearbit.com/google.com', 'Technology', 'Leading technology company known for search, cloud, and AI products', 'Advanced', ARRAY['Software Engineer', 'Product Manager', 'Data Scientist', 'UX Designer']),
('Amazon', 'amazon', 'https://logo.clearbit.com/amazon.com', 'E-commerce & Cloud', 'Global e-commerce and cloud computing leader', 'Advanced', ARRAY['Software Development Engineer', 'Product Manager', 'Solutions Architect', 'Data Engineer']),
('Microsoft', 'microsoft', 'https://logo.clearbit.com/microsoft.com', 'Technology', 'Software and cloud services giant', 'Intermediate', ARRAY['Software Engineer', 'Cloud Solutions Architect', 'Program Manager', 'Data Scientist']),
('Meta', 'meta', 'https://logo.clearbit.com/meta.com', 'Social Media & Technology', 'Social media and metaverse technology company', 'Advanced', ARRAY['Software Engineer', 'Product Designer', 'Data Scientist', 'Research Scientist']),
('Apple', 'apple', 'https://logo.clearbit.com/apple.com', 'Technology & Consumer Electronics', 'Premium consumer electronics and software company', 'Advanced', ARRAY['Software Engineer', 'Hardware Engineer', 'Product Designer', 'Machine Learning Engineer']),
('Netflix', 'netflix', 'https://logo.clearbit.com/netflix.com', 'Streaming & Entertainment', 'Leading streaming entertainment service', 'Advanced', ARRAY['Software Engineer', 'Data Engineer', 'Content Strategist', 'Product Manager']),
('Tesla', 'tesla', 'https://logo.clearbit.com/tesla.com', 'Automotive & Energy', 'Electric vehicles and clean energy company', 'Advanced', ARRAY['Software Engineer', 'Mechanical Engineer', 'Automation Engineer', 'Data Scientist']),
('Stripe', 'stripe', 'https://logo.clearbit.com/stripe.com', 'Fintech', 'Online payment processing platform', 'Intermediate', ARRAY['Software Engineer', 'Product Manager', 'Solutions Engineer', 'Data Analyst']);

-- Seed Google questions
INSERT INTO public.company_questions (company_id, question_text, question_type, difficulty, role, experience_level, tags) VALUES
((SELECT id FROM public.company_templates WHERE slug = 'google'), 'Design a URL shortening service like bit.ly. Consider scalability, collision handling, and analytics.', 'System Design', 'Hard', 'Software Engineer', 'Senior', ARRAY['system-design', 'scalability', 'distributed-systems']),
((SELECT id FROM public.company_templates WHERE slug = 'google'), 'Implement an LRU (Least Recently Used) cache with O(1) time complexity for both get and put operations.', 'Coding', 'Medium', 'Software Engineer', 'Mid', ARRAY['data-structures', 'algorithms', 'caching']),
((SELECT id FROM public.company_templates WHERE slug = 'google'), 'Tell me about a time when you had to make a difficult technical decision. What was the outcome?', 'Behavioral', 'Medium', 'Software Engineer', 'Senior', ARRAY['leadership', 'decision-making']),
((SELECT id FROM public.company_templates WHERE slug = 'google'), 'How would you design Google Maps? Focus on the backend architecture and data structures.', 'System Design', 'Hard', 'Software Engineer', 'Staff', ARRAY['system-design', 'geospatial', 'scalability']),
((SELECT id FROM public.company_templates WHERE slug = 'google'), 'Given a binary tree, find the maximum path sum. The path can start and end at any node.', 'Coding', 'Hard', 'Software Engineer', 'Mid', ARRAY['trees', 'dynamic-programming', 'algorithms']),
((SELECT id FROM public.company_templates WHERE slug = 'google'), 'Explain how you would optimize a slow database query. Walk me through your debugging process.', 'Technical', 'Medium', 'Software Engineer', 'Mid', ARRAY['databases', 'optimization', 'debugging']),
((SELECT id FROM public.company_templates WHERE slug = 'google'), 'Design a distributed rate limiter that can handle millions of requests per second.', 'System Design', 'Hard', 'Software Engineer', 'Senior', ARRAY['distributed-systems', 'rate-limiting', 'scalability']);

-- Seed Amazon questions
INSERT INTO public.company_questions (company_id, question_text, question_type, difficulty, role, experience_level, tags) VALUES
((SELECT id FROM public.company_templates WHERE slug = 'amazon'), 'Design Amazon''s product recommendation system. How would you handle real-time updates and personalization?', 'System Design', 'Hard', 'Software Development Engineer', 'Senior', ARRAY['machine-learning', 'recommendation-systems', 'scalability']),
((SELECT id FROM public.company_templates WHERE slug = 'amazon'), 'Tell me about a time when you had to deal with a difficult customer or stakeholder. How did you handle it?', 'Behavioral', 'Medium', 'Software Development Engineer', 'Mid', ARRAY['customer-obsession', 'communication']),
((SELECT id FROM public.company_templates WHERE slug = 'amazon'), 'Implement a function to find the longest palindromic substring in a given string.', 'Coding', 'Medium', 'Software Development Engineer', 'Mid', ARRAY['strings', 'dynamic-programming', 'algorithms']),
((SELECT id FROM public.company_templates WHERE slug = 'amazon'), 'Design a system like Amazon Prime Video. Focus on video streaming, CDN, and handling peak loads.', 'System Design', 'Hard', 'Software Development Engineer', 'Staff', ARRAY['streaming', 'cdn', 'distributed-systems']),
((SELECT id FROM public.company_templates WHERE slug = 'amazon'), 'Describe a situation where you had to dive deep into a problem to find the root cause.', 'Behavioral', 'Medium', 'Software Development Engineer', 'Senior', ARRAY['dive-deep', 'problem-solving']),
((SELECT id FROM public.company_templates WHERE slug = 'amazon'), 'Given a list of items with weights and values, solve the 0/1 knapsack problem.', 'Coding', 'Medium', 'Software Development Engineer', 'Mid', ARRAY['dynamic-programming', 'optimization', 'algorithms']),
((SELECT id FROM public.company_templates WHERE slug = 'amazon'), 'How would you design Amazon''s inventory management system across multiple warehouses?', 'System Design', 'Hard', 'Software Development Engineer', 'Senior', ARRAY['distributed-systems', 'inventory', 'consistency']);

-- Seed Microsoft questions
INSERT INTO public.company_questions (company_id, question_text, question_type, difficulty, role, experience_level, tags) VALUES
((SELECT id FROM public.company_templates WHERE slug = 'microsoft'), 'Design a collaborative document editing system like Microsoft Word Online with real-time collaboration.', 'System Design', 'Hard', 'Software Engineer', 'Senior', ARRAY['real-time', 'collaboration', 'conflict-resolution']),
((SELECT id FROM public.company_templates WHERE slug = 'microsoft'), 'Implement a function to reverse a linked list. Can you do it iteratively and recursively?', 'Coding', 'Easy', 'Software Engineer', 'Entry', ARRAY['linked-lists', 'recursion', 'algorithms']),
((SELECT id FROM public.company_templates WHERE slug = 'microsoft'), 'Tell me about a time when you had to learn a new technology quickly to complete a project.', 'Behavioral', 'Medium', 'Software Engineer', 'Mid', ARRAY['learning', 'adaptability']),
((SELECT id FROM public.company_templates WHERE slug = 'microsoft'), 'Design the architecture for Microsoft Teams. Focus on messaging, video calls, and file sharing.', 'System Design', 'Hard', 'Software Engineer', 'Staff', ARRAY['messaging', 'webrtc', 'distributed-systems']),
((SELECT id FROM public.company_templates WHERE slug = 'microsoft'), 'Given two sorted arrays, merge them into a single sorted array with O(n+m) time complexity.', 'Coding', 'Easy', 'Software Engineer', 'Entry', ARRAY['arrays', 'sorting', 'algorithms']),
((SELECT id FROM public.company_templates WHERE slug = 'microsoft'), 'How would you design a cloud storage service like OneDrive? Consider sync, versioning, and sharing.', 'System Design', 'Hard', 'Software Engineer', 'Senior', ARRAY['cloud-storage', 'synchronization', 'distributed-systems']);

-- Seed Meta questions
INSERT INTO public.company_questions (company_id, question_text, question_type, difficulty, role, experience_level, tags) VALUES
((SELECT id FROM public.company_templates WHERE slug = 'meta'), 'Design Facebook''s News Feed. How would you rank posts and handle billions of users?', 'System Design', 'Hard', 'Software Engineer', 'Senior', ARRAY['ranking', 'scalability', 'machine-learning']),
((SELECT id FROM public.company_templates WHERE slug = 'meta'), 'Implement a function to detect cycles in a directed graph using DFS.', 'Coding', 'Medium', 'Software Engineer', 'Mid', ARRAY['graphs', 'dfs', 'algorithms']),
((SELECT id FROM public.company_templates WHERE slug = 'meta'), 'Tell me about a time when you had to make a trade-off between moving fast and ensuring quality.', 'Behavioral', 'Medium', 'Software Engineer', 'Senior', ARRAY['move-fast', 'quality', 'decision-making']),
((SELECT id FROM public.company_templates WHERE slug = 'meta'), 'Design Instagram''s photo storage and delivery system. Consider CDN, image processing, and filters.', 'System Design', 'Hard', 'Software Engineer', 'Staff', ARRAY['cdn', 'image-processing', 'distributed-systems']),
((SELECT id FROM public.company_templates WHERE slug = 'meta'), 'Given a string, find all permutations of the string. Optimize for both time and space.', 'Coding', 'Medium', 'Software Engineer', 'Mid', ARRAY['backtracking', 'recursion', 'algorithms']),
((SELECT id FROM public.company_templates WHERE slug = 'meta'), 'How would you design a real-time messaging system like WhatsApp? Focus on delivery guarantees and encryption.', 'System Design', 'Hard', 'Software Engineer', 'Senior', ARRAY['messaging', 'encryption', 'real-time']);

-- Seed Apple questions
INSERT INTO public.company_questions (company_id, question_text, question_type, difficulty, role, experience_level, tags) VALUES
((SELECT id FROM public.company_templates WHERE slug = 'apple'), 'Design the iCloud sync system. How would you handle conflicts and ensure data consistency?', 'System Design', 'Hard', 'Software Engineer', 'Senior', ARRAY['synchronization', 'consistency', 'distributed-systems']),
((SELECT id FROM public.company_templates WHERE slug = 'apple'), 'Implement a binary search tree and write functions for insertion, deletion, and search.', 'Coding', 'Medium', 'Software Engineer', 'Mid', ARRAY['trees', 'data-structures', 'algorithms']),
((SELECT id FROM public.company_templates WHERE slug = 'apple'), 'Describe a project where you had to focus on user experience and design. What was your approach?', 'Behavioral', 'Medium', 'Software Engineer', 'Mid', ARRAY['user-experience', 'design', 'attention-to-detail']),
((SELECT id FROM public.company_templates WHERE slug = 'apple'), 'How would you design Siri''s backend architecture? Consider speech recognition, NLP, and response generation.', 'System Design', 'Hard', 'Software Engineer', 'Staff', ARRAY['nlp', 'machine-learning', 'distributed-systems']),
((SELECT id FROM public.company_templates WHERE slug = 'apple'), 'Given a matrix, find the shortest path from top-left to bottom-right. You can only move right or down.', 'Coding', 'Medium', 'Software Engineer', 'Mid', ARRAY['dynamic-programming', 'matrices', 'algorithms']),
((SELECT id FROM public.company_templates WHERE slug = 'apple'), 'Design the Apple Music streaming service. Focus on audio quality, offline mode, and recommendations.', 'System Design', 'Hard', 'Software Engineer', 'Senior', ARRAY['streaming', 'caching', 'recommendation-systems']);

-- Add more questions for variety (Netflix, Tesla, Stripe)
INSERT INTO public.company_questions (company_id, question_text, question_type, difficulty, role, experience_level, tags) VALUES
((SELECT id FROM public.company_templates WHERE slug = 'netflix'), 'Design Netflix''s video recommendation algorithm. How would you personalize content for millions of users?', 'System Design', 'Hard', 'Software Engineer', 'Senior', ARRAY['machine-learning', 'recommendation-systems', 'personalization']),
((SELECT id FROM public.company_templates WHERE slug = 'netflix'), 'Implement an algorithm to find the top K most frequently watched shows from a stream of viewing data.', 'Coding', 'Medium', 'Software Engineer', 'Mid', ARRAY['heap', 'streaming-data', 'algorithms']),
((SELECT id FROM public.company_templates WHERE slug = 'netflix'), 'Tell me about a time when you had to optimize system performance. What metrics did you focus on?', 'Behavioral', 'Medium', 'Software Engineer', 'Senior', ARRAY['optimization', 'performance', 'metrics']),
((SELECT id FROM public.company_templates WHERE slug = 'tesla'), 'Design the software architecture for Tesla''s autopilot system. Consider real-time processing and safety.', 'System Design', 'Hard', 'Software Engineer', 'Staff', ARRAY['real-time', 'autonomous-systems', 'safety-critical']),
((SELECT id FROM public.company_templates WHERE slug = 'tesla'), 'Implement a PID controller algorithm for vehicle speed control.', 'Coding', 'Hard', 'Software Engineer', 'Senior', ARRAY['control-systems', 'algorithms', 'embedded']),
((SELECT id FROM public.company_templates WHERE slug = 'stripe'), 'Design a payment processing system that can handle millions of transactions per day with high reliability.', 'System Design', 'Hard', 'Software Engineer', 'Senior', ARRAY['payments', 'reliability', 'distributed-systems']),
((SELECT id FROM public.company_templates WHERE slug = 'stripe'), 'Implement idempotency for API requests. How would you prevent duplicate charges?', 'Technical', 'Medium', 'Software Engineer', 'Mid', ARRAY['api-design', 'idempotency', 'payments']);
